# Generated by Django 4.2.6 on 2023-11-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregaFinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='link',
        ),
    ]
